### PR TITLE
Update Types.hs copyright notice

### PR DESCRIPTION
**Pull request by siddhartha-sharma**

### CODE REVIEW

**Comment by gambogi** [comment]
All of the PRs you just made should have been consolidated.

**Comment by siddhartha-sharma** [comment]
newbie here, was helping a collaborator @watashi; can you please guide me with consolidating multiple PRs ?

**Comment by gambogi** [comment]
It looks like you made all of the code changes in browser, but I would recommend making a proper fork. Once you've made all the relevant changes, make a PR with all of them.

Update *.hs is also not a descriptive commit message.

**Comment by siddhartha-sharma** [comment]
I get it. I will keep in mind. Will work out next time.

**Pull request closed without merging**
