### PR TITLE
Update LICENSE, 2014 onwards!

### PR DESCRIPTION
**Pull request by siddhartha-sharma**

### CODE REVIEW

**Comment by watashi** [comment]
Can you update the copyright headers in source files also?

**Comment by siddhartha-sharma** [comment]
@watashi surely! I'll do that tomorrow, is that cool?

**Comment by siddhartha-sharma** [comment]
@watashi done! please merge the PRs...

**Comment by watashi** [comment]
Please keep them in a single pr and commit. Thanks.

**Comment by siddhartha-sharma** [comment]
done! :)

**Pull request closed without merging**
