### PR TITLE
Made ghc 8 not yell at me

### PR DESCRIPTION
**Pull request by SamuelSchlesinger**
I ran cabal build and fixed every warning that came up. I'm running on GHC 8.0.1.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by niteria** [comment]
This breaks CI for GHC 7.8.4. Would you mind fixing that?

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by 5outh** [comment]
Looks like you'll need some version-bound conditionals in there?

**Comment by phadej** [comment]
the redundant constraints are redundant only with base-4.8+ (GHC7.10+), before `Monad m` didn't imply `Functor/Applicative`. So it's either warnings, adding `-fno-redundant-constraints` (with CPP or to cabal-file, as that flag works only on GHC8.0+), CPP for different constraints, or dropping 7.8 support. IMHO the first option is best atm.

**Comment by SamuelSchlesinger** [comment]
Yeah I agree with @phadej. I realized this at one point when I was using my version with an earlier GHC and forgot to come back here and make that clear. Real interested in helping out though if there's anything real to do, honestly this was my favorite read codewise in a while.

**Comment by niteria** [comment]
Sounds like everyone is ok with just closing this. Thanks to everyone involved!

**Pull request closed without merging**
